
project_id = "mlrouwmtqdrlbwhacmic"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://cam-alert.lovable.app"
additional_redirect_urls = ["https://cam-alert.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation = true
persist_session = true

[edge_functions]
enabled = true
port = 54323

[functions.send-motion-alert]
verify_jwt = false

[functions.camera-proxy]
verify_jwt = true

[functions.duckdns-update]
verify_jwt = true

[functions.save-duckdns-token]
verify_jwt = true
